//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidZaniaPhotoPrintingAdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lineitem()
        {
            this.itemphotoes = new HashSet<itemphoto>();
        }
    
        public string lineitem_id { get; set; }
        public string p_id { get; set; }
        public string product_id { get; set; }
        public string photos { get; set; }
        public decimal item_amount { get; set; }
        public string status { get; set; }
        public int quantity { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemphoto> itemphotoes { get; set; }
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
