//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidZaniaPhotoPrintingAdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public printer()
        {
            this.itemphotoes = new HashSet<itemphoto>();
        }
    
        public string printer_id { get; set; }
        public string name { get; set; }
        public bool status { get; set; }
        public string error { get; set; }
        public System.DateTime updated_at { get; set; }
        public string updated_by { get; set; }
        public string port { get; set; }
        public bool manuallyOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemphoto> itemphotoes { get; set; }
        public virtual staff staff { get; set; }
    }
}
