//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public decimal pro_price { get; set; }
        public decimal pro_gst { get; set; }
        public string pro_description { get; set; }
        public string pro_image { get; set; }
        public bool pro_visibility { get; set; }
    }
}
