//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public string purchase_id { get; set; }
        public string softcopy { get; set; }
        public string eccopy { get; set; }
        public string a5copy { get; set; }
        public string mgcopy { get; set; }
        public string kccopy { get; set; }
        public string lrcopy { get; set; }
        public string json { get; set; }
        public Nullable<int> total_price { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public string purchase_status { get; set; }
        public string email_status { get; set; }
        public string hardcopy_status { get; set; }
        public string magnet_status { get; set; }
        public string ecard_status { get; set; }
        public string keychain_status { get; set; }
    }
}
