//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<payment_status> payment_status { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<test> tests { get; set; }
    }
}
